import { AnswerType } from '../enums/AnswerType';
import { LeaderboardConfiguration } from '../enums/LeaderboardConfiguration';
import { QuestionType } from '../enums/QuestionType';
import { QuizState } from '../enums/QuizState';
import { IFreetextAnswer } from '../interfaces/answeroptions/IFreetextAnswer';
import { IQuiz } from '../interfaces/quizzes/IQuizEntity';

export const generateQuiz = (name: string): IQuiz => {
  return {
    name,
    readingConfirmationRequested: false,
    privateKey: 'test',
    state: QuizState.Inactive,
    currentStartTimestamp: 0,
    currentQuestionIndex: -1,
    sessionConfig: {
      leaderboardAlgorithm: LeaderboardConfiguration.TimeBased,
      music: {
        enabled: {
          lobby: true,
          countdownRunning: true,
          countdownEnd: true,
        },
        volumeConfig: {
          global: 60,
          lobby: 60,
          countdownRunning: 60,
          countdownEnd: 60,
          useGlobalVolume: true,
        },
        titleConfig: {
          lobby: 'Song0',
          countdownRunning: 'Song0',
          countdownEnd: 'Song0',
        },
      },
      nicks: {
        memberGroups: [],
        maxMembersPerGroup: 10,
        autoJoinToGroup: false,
        blockIllegalNicks: true,
        restrictToCasLogin: false,
        selectedNicks: [],
      },
      theme: 'theme-Material',
      readingConfirmationEnabled: true,
      showResponseProgress: true,
      confidenceSliderEnabled: true,
    },
    questionList: [
      {
        TYPE: QuestionType.SingleChoiceQuestion,
        displayAnswerText: true,
        questionText: 'abc',
        timer: 60,
        answerOptionList: [
          {
            TYPE: AnswerType.DefaultAnswerOption,
            answerText: 'answer1',
            isCorrect: true,
          }, {
            TYPE: AnswerType.DefaultAnswerOption,
            answerText: 'answer2',
            isCorrect: false,
          },
        ],
      }, {
        TYPE: QuestionType.MultipleChoiceQuestion,
        displayAnswerText: true,
        questionText: 'abc',
        timer: 60,
        answerOptionList: [
          {
            TYPE: AnswerType.DefaultAnswerOption,
            answerText: 'answer1',
            isCorrect: true,
          }, {
            TYPE: AnswerType.DefaultAnswerOption,
            answerText: 'answer2',
            isCorrect: false,
          },
        ],
      }, {
        TYPE: QuestionType.RangedQuestion,
        displayAnswerText: true,
        questionText: 'abc',
        timer: 60,
        rangeMin: 0,
        rangeMax: 0,
        correctValue: 0,
      }, {
        TYPE: QuestionType.FreeTextQuestion,
        displayAnswerText: true,
        questionText: 'abc',
        timer: 60,
        answerOptionList: [
          {
            TYPE: AnswerType.FreeTextAnswerOption,
            answerText: '',
            configCaseSensitive: true,
            configTrimWhitespaces: true,
            configUseKeywords: true,
            configUsePunctuation: true,
          } as IFreetextAnswer,
        ],
      }, {
        TYPE: QuestionType.SurveyQuestion,
        displayAnswerText: true,
        questionText: 'abc',
        timer: 60,
        answerOptionList: [
          {
            TYPE: AnswerType.DefaultAnswerOption,
            answerText: 'answer1',
            isCorrect: false,
          }, {
            TYPE: AnswerType.DefaultAnswerOption,
            answerText: 'answer2',
            isCorrect: false,
          },
        ],
      }, {
        TYPE: QuestionType.YesNoSingleChoiceQuestion,
        displayAnswerText: true,
        questionText: 'abc',
        timer: 60,
        answerOptionList: [
          {
            TYPE: AnswerType.DefaultAnswerOption,
            answerText: 'Yes',
            isCorrect: false,
          }, {
            TYPE: AnswerType.DefaultAnswerOption,
            answerText: 'No',
            isCorrect: false,
          },
        ],
      }, {
        TYPE: QuestionType.TrueFalseSingleChoiceQuestion,
        displayAnswerText: true,
        questionText: 'abc',
        timer: 60,
        answerOptionList: [
          {
            TYPE: AnswerType.DefaultAnswerOption,
            answerText: 'True',
            isCorrect: false,
          }, {
            TYPE: AnswerType.DefaultAnswerOption,
            answerText: 'False',
            isCorrect: false,
          },
        ],
      },
    ],
  };
};

export const generateLegacyQuiz = (name: string) => {
  return {
    hashtag: name,
    isFirstStart: false,
    questionList: [
      {
        hashtag: name,
        isFirstStart: false,
        questionText: '###The 100€ question\n\nGerman RTL-Show "Wer wird Millionär?" from December 7$^{th}$, 2015.\n\nWhat does the black widow "think" after the mating about the male spider?\n\nhttps://www.youtube.com/watch?v=6Z-rh7bkpIg',
        timer: 60,
        startTime: 0,
        questionIndex: 0,
        displayAnswerText: true,
        answerOptionList: [
          {
            hashtag: name,
            questionIndex: 0,
            answerText: 'Igitt, so behaart!',
            answerOptionNumber: 0,
            isCorrect: false,
            type: 'DefaultAnswerOption',
          },
          {
            hashtag: name,
            questionIndex: 0,
            answerText: 'Wie süß er schläft!',
            answerOptionNumber: 1,
            isCorrect: false,
            type: 'DefaultAnswerOption',
          },
          {
            hashtag: name,
            questionIndex: 0,
            answerText: 'Lecker!',
            answerOptionNumber: 2,
            isCorrect: true,
            type: 'DefaultAnswerOption',
          },
          {
            hashtag: name,
            questionIndex: 0,
            answerText: 'Manni war besser!',
            answerOptionNumber: 3,
            isCorrect: false,
            type: 'DefaultAnswerOption',
          },
        ],
        showOneAnswerPerRow: false,
        type: 'SingleChoiceQuestion',
      },
      {
        hashtag: name,
        isFirstStart: true,
        questionText: '###Schätzfrage\n\nWas schätzen Sie, wie viele Lehrende haben bisher in allen deutschsprachigen Ländern zusammengenommen das Feedback- und Abstimmungssystem **ARSnova** im Unterricht eingesetzt?\n\nDie Statistik finden Sie im [ARSnova-Projektblog](https://arsnova.eu/blog/).\n\n![Siehe: https://arsnova.thm.de/blog/](https://arsnova.thm.de/blog/wp-content/uploads/2015/07/ARSnova-Produktprospekt.png)',
        timer: 600,
        startTime: 0,
        questionIndex: 1,
        displayAnswerText: false,
        answerOptionList: [],
        type: 'RangedQuestion',
        rangeMin: 1000.2123,
        rangeMax: 10000.2123,
        correctValue: 7300,
      },
      {
        hashtag: name,
        isFirstStart: true,
        questionText: '###Die Millionenfrage\n\nRTL-Show "Wer wird Millionär?" vom 7. 12. 2015\n\nAus insgesamt wie vielen Steinchen besteht der klassische von Ernő Rubik erfundene Zauberwürfel?\n\nhttps://www.youtube.com/watch?v=GSd66EnQjms',
        timer: 120,
        startTime: 0,
        questionIndex: 2,
        displayAnswerText: true,
        answerOptionList: [
          {
            hashtag: name,
            questionIndex: 2,
            answerText: '28 Steinchen',
            answerOptionNumber: 0,
            isCorrect: false,
            type: 'DefaultAnswerOption',
          },
          {
            hashtag: name,
            questionIndex: 2,
            answerText: '26 Steinchen',
            answerOptionNumber: 1,
            isCorrect: true,
            type: 'DefaultAnswerOption',
          },
          {
            hashtag: name,
            questionIndex: 2,
            answerText: '24 Steinchen',
            answerOptionNumber: 2,
            isCorrect: false,
            type: 'DefaultAnswerOption',
          },
          {
            hashtag: name,
            questionIndex: 2,
            answerText: '22 Steinchen',
            answerOptionNumber: 3,
            isCorrect: false,
            type: 'DefaultAnswerOption',
          },
        ],
        showOneAnswerPerRow: false,
        type: 'SingleChoiceQuestion',
      },
      {
        hashtag: name,
        isFirstStart: false,
        questionText: '###Wie finden Sie die App?',
        timer: 10,
        startTime: 0,
        questionIndex: 3,
        displayAnswerText: true,
        answerOptionList: [
          {
            hashtag: name,
            questionIndex: 3,
            answerText: ':+1:',
            answerOptionNumber: 0,
            isCorrect: false,
            type: 'DefaultAnswerOption',
          },
          {
            hashtag: name,
            questionIndex: 3,
            answerText: ':-1:',
            answerOptionNumber: 1,
            isCorrect: false,
            type: 'DefaultAnswerOption',
          },
        ],
        showOneAnswerPerRow: false,
        type: 'SurveyQuestion',
        multipleSelectionEnabled: false,
      },
      {
        hashtag: name,
        isFirstStart: false,
        questionText: '',
        timer: 40,
        startTime: 0,
        questionIndex: 4,
        displayAnswerText: false,
        answerOptionList: [
          {
            hashtag: name,
            questionIndex: 4,
            answerText: '',
            answerOptionNumber: 0,
            isCorrect: false,
            type: 'DefaultAnswerOption',
          },
          {
            hashtag: name,
            questionIndex: 4,
            answerText: '',
            answerOptionNumber: 1,
            isCorrect: false,
            type: 'DefaultAnswerOption',
          },
        ],
        showOneAnswerPerRow: false,
        type: 'SingleChoiceQuestion',
      },
    ],
    configuration: {
      hashtag: name,
      music: {
        hashtag: name,
        isUsingGlobalVolume: true,
        lobbyEnabled: false,
        lobbyTitle: 'Song0',
        lobbyVolume: 100,
        countdownRunningEnabled: false,
        countdownRunningTitle: 'Song1',
        countdownRunningVolume: 100,
        countdownEndEnabled: false,
        countdownEndTitle: 'Song1',
        countdownEndVolume: 100,
      },
      nicks: {
        hashtag: name,
        selectedValues: [
          'Edsger Dijkstra',
          'Konrad Zuse',
          'Alan Turing',
          'Galileo Galilei',
          'Johannes Kepler',
          'Blaise Pascal',
          'Christiaan Huygens',
          'Marie Curie',
          'Isaac Newton',
          'Robert Boyle',
          'Gottfried Leibniz',
          'Johannes Gutenberg',
          'Leonardo Fibonacci',
          'André Ampère',
          'Archimedes',
          'Aristoteles',
          'Leonardo Da Vinci',
          'Charles Darwin',
          'Albert Einstein',
          'Euklid',
        ],
        blockIllegal: true,
        restrictToCASLogin: false,
      },
      theme: 'theme-Material',
      readingConfirmationEnabled: true,
      showResponseProgress: false,
      confidenceSliderEnabled: true,
    },
    type: 'DefaultQuestionGroup',
  };
};
